### ILP(整数线性规划)

$$
min\,z = \sum_{i = 1}^6 x_i, \\

s.t.
\begin{cases}
    x_1 + x_6 \geq 35, \\
    x_1 + x_2 \geq 40, \\
    x_2 + x_3 \geq 50, \\
    x_3 + x_4 \geq 45, \\
    x_4 + x_5 \geq 55, \\
    x_5 + x_6 \geq 30, \\
    x_i \geq 0\,且为整数,i = 1,2,...,6.
\end{cases}    
$$


In [9]:

import cvxpy as cp
import numpy as np

x = cp.Variable(6, integer = True)
fun = cp.Minimize(sum(x))
cons = [
    x[5] + x[0] >= 35,  # 注意两个下表可以互换，有对称性
    x[0] + x[1] >= 40,  # 便于下方用for简化长式子
    x[1] + x[2] >= 50,
    x[2] + x[3] >= 45,
    x[3] + x[4] >= 55,
    x[4] + x[5] >= 30,
    x >= 0
]

a = np.array([35,40,50,45,55,30])
cons2 = [x >= 0]

for i in range(6):
    cons2.append(x[(i - 1) % 6] + x[i] >= a[i])

problem = cp.Problem(fun,cons2)

problem.solve()

print(f"最优解为: {x.value}")
print(f"最优值为: {problem.value}")


最优解为: [35.  5. 45. -0. 55. -0.]
最优值为: 140.0



### 问题2

$$
    min\,z = \sum_{i = 1}^4 \sum_{j = 1}^5 c_{ij}x_{ij}, \\

    s.t.
     \begin{cases}
        \sum_{i = 1}^4 x_{ij} = 1,~~ j = 1,2,...5, \\
        \sum_{j = 1}^5 x_{ij} \leq 2,~~ i = 1,2,3,4, \\
        x_{ij} = 0或1,~~ i = 1,2,3,4,j = 1,2,...,5.
     \end{cases}
$$



In [11]:

import cvxpy as cp
import numpy as np

c = np.loadtxt(r"mod/规划-cvx解ILP.txt")
x = cp.Variable((4,5), boolean = True)

fun = cp.Minimize(cp.sum(cp.multiply(c,x)))
cons = [
    cp.sum(x,axis = 0) == 1,
    cp.sum(x,axis = 1) <= 2
]

problem = cp.Problem(fun,cons)
problem.solve()

print(f"最优解为: {x.value}")
print(f"最优值为: {problem.value}")


最优解为: [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
最优值为: 63.8
