
#### cvxpy解线性规划

$max \, z = 70x_1 + 50x_2 + 60x_3 $
<br><br>
$s.t. \begin{cases} 2x_1 + 4x_2 + 3x_3 \leq 150, \\ 3x_1 + x_2 + 5x_3 \leq 160, \\ 7x_1 + 3x_2 + 5x_3 \leq 200, \\ x \geq 0,i = 1,2,3 \end{cases}$


In [9]:

import cvxpy as cp
import numpy as np

c = np.array([70,50,60])
a = np.array([
        [2,4,3],
        [3,1,5],
        [7,3,5]
    ])
b = np.array([150,160,200])

x = cp.Variable(3,pos = True)
fun = cp.Maximize(c @ x)
st = [a @ x <= b]

problem = cp.Problem(fun,st)
problem.solve()
print(f'最优解为: {x.value}')
print(f'最优值为: {problem.value}')


[[2.00 4.00 3.00]
 [3.00 1.00 5.00]
 [7.00 3.00 5.00]] @ var197 <= [150. 160. 200.]
最优解为: [ 8.35184614 21.98820975 15.11448955]
最优值为: 2590.909090524814



#### 2

$
max\,z = 1.15x_{41} + 1.40x_{23} + 1.25x_{32} + 1.06x_{54} \\

s.t. = \begin{cases}
			x_{11} + x_{14} = 100000, \\
			x_{21} + x_{23} + x_{24} = 1.06x_{14}, \\
			x_{31} + x_{32} + x_{34} = 1.15x_{11} + 1.06x_{24}, \\
			x_{41} + x_{44} = 1.15x_{21} + 1.06x_{34}, \\
			x_{54} = 1.15x_{31} + 1.06x_{44}, \\
			x_{32} \leq 40000,~~~ x_{23} \leq 30000, \\
			x_{ij} \geq 0,~~~ i = 1,2,3,4,5;\,j = 1,2,3,4
		\end{cases}
$

In [23]:

import cvxpy as cp

x = cp.Variable((5,4),pos = True)

fun = cp.Maximize(1.15 * x[3,0] + 1.40 * x[1,2] + 1.25 * x[2,1] + 1.06 * x[4,3])

st = [
    x[0,0] + x[0,3] == 100000,
    x[1,0] + x[1,2] + x[1,3] == 1.06 * x[0,3],
    x[2,0] + x[2,1] + x[2,3] == 1.15 * x[0,0] + 1.06 * x[1,3],
    x[3,0] + x[3,3] == 1.15 * x[1,0] + 1.06 * x[2,3],
    x[4,3] == 1.15 * x[2,0] + 1.06 * x[3,3],
    x[2,1] <= 40000,   x[1,2] <= 30000,
]

problem = cp.Problem(fun,st)
problem.solve()

print(f'最优解为: {x.value}')
print(f'最优值为: {problem.value}')



最优解为: [[5.79191170e+04 5.47194224e+03 5.47194224e+03 4.20808830e+04]
 [1.46057338e+04 5.47194224e+03 2.99999997e+04 2.52222218e-03]
 [1.48696169e+04 3.99999969e+04 5.47194224e+03 1.17373734e+04]
 [2.92382072e+04 5.47194224e+03 5.47194224e+03 2.45764330e-03]
 [5.47194224e+03 5.47194224e+03 5.47194224e+03 1.71000620e+04]]
最优值为: 143749.99973901053
